from enum import Enum, auto


# 定义Action枚举
class Action(Enum):
    LAUNCH_APP = auto()
    STOP_APP = auto()
    CLICK = auto()
    INPUT = auto()
    SWIPE = auto()
    PULL_TO_REFRESH = auto()
    SWIPE_PAGINATION = auto()
    WAIT_FOR_ELEMENT = auto()
    EXTRACT_CONTENT = auto()
    LONG_CLICK = auto()
    DOUBLE_CLICK = auto()
    SCROLL = auto()
    DRAG_AND_DROP = auto()
    PINCH = auto()
    ZOOM = auto()
    HARD_KEY_PRESS = auto()
    HARD_KEY_LONG_PRESS = auto()
    TAKE_SCREENSHOT = auto()
    GET_TEXT = auto()
    SET_TEXT = auto()
    TOGGLE_SWITCH = auto()
    SELECT_FROM_DROPDOWN = auto()
    BACK = auto()
    HOME = auto()
    LAUNCH_ACTIVITY = auto()
    RESTART_APP = auto()
    CLEAR_DATA = auto()
    NOTIFICATION = auto()
    OPEN_URL = auto()

# 定义Direction枚举
class Direction(Enum):
    UP = auto()
    DOWN = auto()
    LEFT = auto()
    RIGHT = auto()

# 定义SelectorType枚举
class SelectorType(Enum):
    TEXT = auto()
    RESOURCE_ID = auto()
    DESCRIPTION = auto()
    XPATH = auto()
    CLASS_NAME = auto()
    INDEX = auto()
    PACKAGE_NAME = auto()
    CONTENT_DESC = auto()
    CHECKABLE = auto()
    CHECKED = auto()
    CLICKABLE = auto()
    ENABLED = auto()
    FOCUSABLE = auto()
    FOCUSED = auto()
    LONG_CLICKABLE = auto()
    SCROLLABLE = auto()
    SELECTED = auto()
    BOUNDS = auto()
    CHILD = auto()
    SIBLING = auto()
    PARENT = auto()
    TAG_NAME = auto()